package com.github.cuidok.oa.server.user;

import com.github.cuidok.oa.server.encryptor.LoginVerificationKeyDecryptor;
import com.github.cuidok.oa.server.user.mapper.UserInsertMapper;
import com.github.cuidok.oa.server.user.model.User;
import com.github.cuidok.oa.server.user.model.UserDetail;
import com.github.cuidok.oa.server.user.model.UserInfo;
import com.github.cuidok.oa.server.user.model.UserLoginParam;
import com.github.cuidok.oa.server.user.model.UserRegisterParam;
import com.github.cuidok.oa.server.verification.LoginVerificationCodeService;
import com.github.cuidok.oa.server.verification.LoginVerificationContainer;
import com.github.cuidok.oa.server.verification.LoginVerificationKeyService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class UserQueryServiceTest {

    @Autowired
    private UserLoginService userLoginService;

    @Autowired
    private UserRegisterService userRegisterService;

    @Autowired
    private LoginVerificationKeyService loginVerificationKeyService;

    @Autowired
    private LoginVerificationCodeService loginVerificationCodeService;

    @Autowired
    private LoginVerificationKeyDecryptor loginVerificationKeyDecryptor;

    @Autowired
    private LoginVerificationContainer loginVerificationContainer;

    @Autowired
    private UserQueryService userQueryService;

    @Autowired
    private UserTokenParse userTokenParse;

    @Test
    void queryUserInfo() {

        // Register
        UserRegisterParam param = new UserRegisterParam();
        param.setUsername("T_" + System.currentTimeMillis());
        param.setNickName("T_nickname");
        param.setPassword("T_password123");
        param.setEmail("T_" + System.currentTimeMillis() + "@test.com");
        userRegisterService.register(param);

        // Get the login verification code
        String key = loginVerificationKeyService.generateKey();
        loginVerificationCodeService.generateCodeImage(key);

        // Get the login verification code generated by system
        String keyOriginal = loginVerificationKeyDecryptor.decrypt(key);
        String code = loginVerificationContainer.get(keyOriginal).get().getCode();

        // Login
        UserLoginParam loginParam = new UserLoginParam();
        loginParam.setUsername(param.getUsername());
        loginParam.setPassword(param.getPassword());
        loginParam.setLoginVerificationKey(key);
        loginParam.setLoginVerificationCode(code);

        // Get the token
        String token = userLoginService.login(loginParam);
        assertNotNull(token);

        // Parse the user token
        UserDetail userDetail = userTokenParse.parseUserToken(token);

        // Query the user information
        UserInfo userInfo = userQueryService.queryUserInfo(token);
        assertNotNull(userInfo);
        assertEquals(userDetail.getId(), userInfo.getId());
        assertEquals(param.getUsername(), userInfo.getUsername());
        assertEquals(param.getNickName(), userInfo.getNickName());
        assertEquals(param.getEmail(), userInfo.getEmail());
    }
}